const KEY='pathOfSignsDataV2';
const starterCrystals=[
{name:'Unakite',image:'',appearance:'Mottled green and salmon-pink stone, often earthy and soft-looking.',traditional:'Balance, gentle growth, patience, emotional healing.',uses:'Heart work, grounding, gentle emotional reflection, patience during change.',chakra:'Heart chakra is the most common association.',element:'Earth + Water',care:'Avoid harsh chemicals. Clean with a soft cloth. Many people prefer smoke, sound, moonlight, or a brief rinse instead of soaking.',drawn:'The first crystal I picked up from my starter collection. Not sure why I picked it — I was just drawn to it.',myNotes:'',experiences:'',experiment:''},
{name:'Amethyst',image:'',appearance:'Purple quartz ranging from pale lavender to deep violet.',traditional:'Intuition, calm, spiritual awareness, protection.',uses:'Meditation, sleep, reflection, spiritual focus.',chakra:'Third eye and crown chakras.',element:'Air + Water',care:'Keep out of long direct sunlight to reduce fading. Clean gently.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Clear Quartz',image:'',appearance:'Clear to cloudy quartz, sometimes with veils or inclusions.',traditional:'Clarity, focus, amplification, cleansing.',uses:'Intentions, charging other stones, meditation, clarity work.',chakra:'All chakras, especially crown.',element:'All elements / amplification.',care:'Durable, but still avoid harsh knocks. Clean with a soft cloth or brief rinse.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Rose Quartz',image:'',appearance:'Soft pink quartz, often cloudy or milky.',traditional:'Love, compassion, gentleness, emotional softness.',uses:'Self-kindness, heart work, soothing, relationships.',chakra:'Heart chakra.',element:'Water.',care:'Can fade in strong sunlight. Clean gently.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Green Aventurine',image:'',appearance:'Green quartz-like stone, sometimes sparkly from mica inclusions.',traditional:'Luck, opportunity, growth, optimism.',uses:'Manifestation, prosperity, new beginnings, opportunities.',chakra:'Heart chakra.',element:'Earth.',care:'Clean gently. Good everyday stone.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Lapis Lazuli',image:'',appearance:'Deep blue stone often with gold pyrite flecks and white calcite.',traditional:'Wisdom, truth, insight, self-expression.',uses:'Discernment, intuition, speaking truth, study.',chakra:'Third eye and throat chakras.',element:'Air + Water.',care:'Avoid soaking and harsh cleaners. Wipe with a soft cloth.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Tiger Eye',image:'',appearance:'Golden-brown banded stone with a silky flash.',traditional:'Courage, confidence, discernment, protection.',uses:'Decision-making, confidence, grounding, action.',chakra:'Solar plexus and root chakras.',element:'Fire + Earth.',care:'Generally sturdy. Clean with soft cloth or brief rinse.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Obsidian',image:'',appearance:'Glossy volcanic glass, usually black.',traditional:'Protection, grounding, boundaries, truth.',uses:'Clearing, grounding, protection, cutting through confusion.',chakra:'Root chakra.',element:'Fire + Earth.',care:'Can chip because it is glass. Handle carefully.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Blue Sodalite',image:'',appearance:'Blue stone often with white streaks or patches.',traditional:'Truth, logic, communication, mental clarity.',uses:'Study, speaking truth, calm thinking.',chakra:'Throat and third eye chakras.',element:'Air + Water.',care:'Avoid long soaking. Wipe gently.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'White Howlite',image:'',appearance:'White or cream stone with gray veining.',traditional:'Calm, patience, rest, stress relief.',uses:'Sleep, stillness, patience, peaceful reflection.',chakra:'Crown chakra.',element:'Air.',care:'Porous stone; avoid soaking and dyes. Wipe gently.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Rhodochrosite',image:'',appearance:'Pink to rose stone, sometimes banded with white.',traditional:'Self-worth, compassion, emotional healing.',uses:'Heart work, inner child reflection, softness.',chakra:'Heart chakra.',element:'Water + Fire.',care:'Softer stone; avoid soaking, salt, and harsh cleaners.',drawn:'',myNotes:'',experiences:'',experiment:''},
{name:'Dalmatian Jasper',image:'',appearance:'Cream or beige stone with black spots.',traditional:'Joy, playfulness, grounding, lightness.',uses:'Balance, friendship, play, emotional reset.',chakra:'Root and sacral chakras.',element:'Earth.',care:'Clean gently. Avoid harsh chemicals.',drawn:'',myNotes:'',experiences:'',experiment:''}
];
function blankData(){return {crystals:starterCrystals.map((c,i)=>({...c,id:'c'+i})),signs:[],symbols:[{id:'s1',name:'Key',traditional:'Access, opportunity, hidden knowledge.',mine:'Discovery, doors opening, finding meaning.'},{id:'s2',name:'Mirror',traditional:'Reflection, truth, self-knowledge.',mine:'Discernment and seeing clearly.'},{id:'s3',name:'Feather',traditional:'Messages, guidance, hope.',mine:'A sign that something is trying to be noticed.'}],moon:[{id:'m1',title:'Moon Water Entry #1',date:'June 2026',notes:'Collected moon water, charged new crystals, drank some with the intention of energy and new beginnings.',result:''}],practices:[]};}
function migrate(old){ if(!old) return blankData(); if(!old.crystals) return blankData(); old.crystals=old.crystals.map((c,i)=>({id:c.id||'c'+i,name:c.name||'New Crystal',image:c.image||'',appearance:c.appearance||'',traditional:c.traditional||'',uses:c.uses||'',chakra:c.chakra||'',element:c.element||'',care:c.care||'',drawn:c.drawn||'',myNotes:c.myNotes||'',experiences:c.experiences||'',experiment:c.experiment||''})); old.signs=old.signs||[]; old.symbols=old.symbols||blankData().symbols; old.moon=old.moon||[]; old.practices=old.practices||[]; return old; }
function load(){return migrate(JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('pathOfSignsDataV1')||'null'))}
function save(){localStorage.setItem(KEY,JSON.stringify(data)); renderAll();}
let data=load();
document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav,.page').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.page).classList.add('active');scrollTo({top:0,behavior:'smooth'});}));
function esc(x=''){return String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function update(list,id,field,val){let item=data[list].find(x=>x.id===id); item[field]=val; localStorage.setItem(KEY,JSON.stringify(data));}
function deleteItem(list,id){if(confirm('Delete this entry?')){data[list]=data[list].filter(x=>x.id!==id);save();}}
function manualSave(){localStorage.setItem(KEY,JSON.stringify(data)); alert('Saved 🌊');}
function bindAutosave(){document.querySelectorAll('[data-save]').forEach(el=>{let k='note.'+el.dataset.save;el.value=localStorage.getItem(k)||el.value||'';el.oninput=()=>localStorage.setItem(k,el.value);});document.querySelectorAll('.save').forEach(b=>b.onclick=()=>alert('Saved 🌊'));}
function handleImage(id,input){const file=input.files[0]; if(!file) return; const reader=new FileReader(); reader.onload=()=>{let c=data.crystals.find(x=>x.id===id); c.image=reader.result; localStorage.setItem(KEY,JSON.stringify(data)); renderAll();}; reader.readAsDataURL(file);}
function removeImage(id){let c=data.crystals.find(x=>x.id===id); c.image=''; save();}
function renderCrystals(){const el=document.getElementById('crystalList'); if(!el)return; el.innerHTML=data.crystals.map(c=>`<article class="crystal-card"><div class="crystal-top"><div><div class="stone-image">${c.image?`<img src="${c.image}" alt="${esc(c.name)}">`:`<div class="stone-placeholder">💎</div>`}</div><div class="image-tools"><input type="file" accept="image/*" onchange="handleImage('${c.id}',this)">${c.image?`<button class="small delete" onclick="removeImage('${c.id}')">Remove Image</button>`:''}</div></div><div class="crystal-title"><input value="${esc(c.name)}" onchange="update('crystals','${c.id}','name',this.value)"><p class="quick">${esc(c.traditional || 'Add traditional meanings here.')}</p><div class="chips">${c.chakra?`<span class="chip">${esc(c.chakra)}</span>`:''}${c.element?`<span class="chip">${esc(c.element)}</span>`:''}</div><p class="source-note">Use this like a gemstone guide: traditional meanings first, then your own observations over time.</p><div class="actions"><button class="small" onclick="manualSave()">Save</button><button class="small delete" onclick="deleteItem('crystals','${c.id}')">Delete</button></div></div></div><div class="accordion"><details><summary>Appearance / How to identify</summary><textarea onchange="update('crystals','${c.id}','appearance',this.value)">${esc(c.appearance)}</textarea></details><details><summary>Traditional meanings</summary><textarea onchange="update('crystals','${c.id}','traditional',this.value)">${esc(c.traditional)}</textarea></details><details><summary>Common uses</summary><textarea onchange="update('crystals','${c.id}','uses',this.value)">${esc(c.uses)}</textarea></details><details><summary>Chakra / energy associations</summary><textarea onchange="update('crystals','${c.id}','chakra',this.value)">${esc(c.chakra)}</textarea></details><details><summary>Element / correspondences</summary><textarea onchange="update('crystals','${c.id}','element',this.value)">${esc(c.element)}</textarea></details><details><summary>Care / cleansing notes</summary><textarea onchange="update('crystals','${c.id}','care',this.value)">${esc(c.care)}</textarea></details><details><summary>Why / what drew me to it</summary><textarea onchange="update('crystals','${c.id}','drawn',this.value)">${esc(c.drawn)}</textarea></details><details><summary>My notes</summary><textarea onchange="update('crystals','${c.id}','myNotes',this.value)">${esc(c.myNotes)}</textarea></details><details><summary>My experiences</summary><textarea onchange="update('crystals','${c.id}','experiences',this.value)">${esc(c.experiences)}</textarea></details><details><summary>Experiment log</summary><textarea onchange="update('crystals','${c.id}','experiment',this.value)">${esc(c.experiment)}</textarea></details></div></article>`).join('');}
function addCrystal(){data.crystals.unshift({id:'c'+Date.now(),name:'New Crystal',image:'',appearance:'',traditional:'',uses:'',chakra:'',element:'',care:'',drawn:'',myNotes:'',experiences:'',experiment:''});save();}
function renderSigns(){const el=document.getElementById('signList');if(!el)return;el.innerHTML=data.signs.map(s=>`<div class="card"><div class="row"><div><label>Date</label><input value="${esc(s.date)}" onchange="update('signs','${s.id}','date',this.value)"></div><div><label>Title</label><input value="${esc(s.title)}" onchange="update('signs','${s.id}','title',this.value)"></div></div><label>What happened</label><textarea onchange="update('signs','${s.id}','happened',this.value)">${esc(s.happened)}</textarea><label>Why it felt significant</label><textarea onchange="update('signs','${s.id}','meaning',this.value)">${esc(s.meaning)}</textarea><label>What eventually happened</label><textarea onchange="update('signs','${s.id}','outcome',this.value)">${esc(s.outcome)}</textarea><div class="actions"><button class="small" onclick="manualSave()">Save</button><button class="small delete" onclick="deleteItem('signs','${s.id}')">Delete</button></div></div>`).join('') || '<div class="card"><p>No signs logged yet. Click + Add Sign.</p></div>';}
function addSign(){data.signs.unshift({id:'g'+Date.now(),date:new Date().toLocaleDateString(),title:'New Sign',happened:'',meaning:'',outcome:''});save();}
function renderSymbols(){const el=document.getElementById('symbolList');if(!el)return;el.innerHTML=data.symbols.map(s=>`<div class="card"><input value="${esc(s.name)}" onchange="update('symbols','${s.id}','name',this.value)"><label>Traditional meaning</label><textarea onchange="update('symbols','${s.id}','traditional',this.value)">${esc(s.traditional)}</textarea><label>My meaning</label><textarea onchange="update('symbols','${s.id}','mine',this.value)">${esc(s.mine)}</textarea><div class="actions"><button class="small" onclick="manualSave()">Save</button><button class="small delete" onclick="deleteItem('symbols','${s.id}')">Delete</button></div></div>`).join('');}
function addSymbol(){data.symbols.unshift({id:'s'+Date.now(),name:'New Symbol',traditional:'',mine:''});save();}
function renderMoon(){const el=document.getElementById('moonList');if(!el)return;el.innerHTML=data.moon.map(m=>`<div class="card"><div class="row"><div><label>Date</label><input value="${esc(m.date)}" onchange="update('moon','${m.id}','date',this.value)"></div><div><label>Title</label><input value="${esc(m.title)}" onchange="update('moon','${m.id}','title',this.value)"></div></div><label>What I did / noticed</label><textarea onchange="update('moon','${m.id}','notes',this.value)">${esc(m.notes)}</textarea><label>What I experienced later</label><textarea onchange="update('moon','${m.id}','result',this.value)">${esc(m.result)}</textarea><div class="actions"><button class="small" onclick="manualSave()">Save</button><button class="small delete" onclick="deleteItem('moon','${m.id}')">Delete</button></div></div>`).join('');}
function addMoon(){data.moon.unshift({id:'m'+Date.now(),date:new Date().toLocaleDateString(),title:'New Moon Entry',notes:'',result:''});save();}
function renderPractices(){const el=document.getElementById('practiceList');if(!el)return;el.innerHTML=data.practices.map(p=>`<div class="card"><div class="row"><div><label>Name</label><input value="${esc(p.name)}" onchange="update('practices','${p.id}','name',this.value)"></div><div><label>Level</label><input value="${esc(p.level)}" onchange="update('practices','${p.id}','level',this.value)"></div></div><label>Purpose</label><textarea onchange="update('practices','${p.id}','purpose',this.value)">${esc(p.purpose)}</textarea><label>Steps</label><textarea onchange="update('practices','${p.id}','steps',this.value)">${esc(p.steps)}</textarea><label>My experience</label><textarea onchange="update('practices','${p.id}','experience',this.value)">${esc(p.experience)}</textarea><div class="actions"><button class="small" onclick="manualSave()">Save</button><button class="small delete" onclick="deleteItem('practices','${p.id}')">Delete</button></div></div>`).join('') || '<div class="card"><p>No practices yet. Click + Add Practice.</p></div>';}
function addPractice(){data.practices.unshift({id:'p'+Date.now(),name:'New Practice',level:'Beginner',purpose:'',steps:'',experience:''});save();}
function downloadBackup(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='path-of-signs-backup.json';a.click();}
function restoreBackup(){const f=document.getElementById('restoreFile').files[0];if(!f)return alert('Choose a backup file first.');const reader=new FileReader();reader.onload=()=>{data=migrate(JSON.parse(reader.result));save();alert('Restored 🌙')};reader.readAsText(f);}
function clearAll(){if(confirm('This clears everything saved in this browser. Continue?')){localStorage.removeItem(KEY);localStorage.removeItem('pathOfSignsDataV1');data=blankData();save();}}
function renderAll(){renderCrystals();renderSigns();renderSymbols();renderMoon();renderPractices();bindAutosave();}
renderAll();
